In [ ]:
data=[6,12,18,24,30,36,42,48,54,60,66,72,78,84,90,96,102,108,114,120,126,132,138,144,150,156,162,168,174,180,186,192,198,204,210,216,222,228,234,240]

In [ ]:
import numpy as np

def splitdata(data,n):
  x=[]
  y=[]

  for i in range (len(data)):
    last=i+n

    if last > len(data)-1:
      break

    seq_x,seq_y=data[i:last],data[last]

    x.append(seq_x)
    y.append(seq_y)

  x=np.array(x)
  y=np.array(y)

  return x,y

In [ ]:
split=4
x,y=splitdata(data,split)

print(x)

[[  6  12  18  24]
 [ 12  18  24  30]
 [ 18  24  30  36]
 [ 24  30  36  42]
 [ 30  36  42  48]
 [ 36  42  48  54]
 [ 42  48  54  60]
 [ 48  54  60  66]
 [ 54  60  66  72]
 [ 60  66  72  78]
 [ 66  72  78  84]
 [ 72  78  84  90]
 [ 78  84  90  96]
 [ 84  90  96 102]
 [ 90  96 102 108]
 [ 96 102 108 114]
 [102 108 114 120]
 [108 114 120 126]
 [114 120 126 132]
 [120 126 132 138]
 [126 132 138 144]
 [132 138 144 150]
 [138 144 150 156]
 [144 150 156 162]
 [150 156 162 168]
 [156 162 168 174]
 [162 168 174 180]
 [168 174 180 186]
 [174 180 186 192]
 [180 186 192 198]
 [186 192 198 204]
 [192 198 204 210]
 [198 204 210 216]
 [204 210 216 222]
 [210 216 222 228]
 [216 222 228 234]]


In [ ]:
n_features=1
print(x.shape)
x=x.reshape(x.shape[0], x.shape[1], n_features)

(36, 4)


In [ ]:
import tensorflow as tf
from tensorflow import keras
from keras.layers import *
from keras.models import *

In [ ]:
model=Sequential()
model.add(LSTM(50,activation='relu',input_shape=(split,n_features)))
model.add(Dense(1))
model.layers
model.compile(optimizer="Adam",loss='mse',metrics='accuracy')
model.fit(x,y,epochs=300,verbose=1)

Epoch 1/300
2/2 [==============================] - 7s 30ms/step - loss: 28428.0547 - accuracy: 0.0000e+00
Epoch 2/300
2/2 [==============================] - 0s 13ms/step - loss: 23044.0469 - accuracy: 0.0000e+00
Epoch 3/300
2/2 [==============================] - 0s 13ms/step - loss: 19679.2617 - accuracy: 0.0000e+00
Epoch 4/300
2/2 [==============================] - 0s 13ms/step - loss: 19431.9512 - accuracy: 0.0000e+00
Epoch 5/300
2/2 [==============================] - 0s 12ms/step - loss: 18004.0684 - accuracy: 0.0000e+00
Epoch 6/300
2/2 [==============================] - 0s 14ms/step - loss: 16044.1162 - accuracy: 0.0000e+00
Epoch 7/300
2/2 [==============================] - 0s 16ms/step - loss: 14649.7344 - accuracy: 0.0000e+00
Epoch 8/300
2/2 [==============================] - 0s 13ms/step - loss: 13594.8867 - accuracy: 0.0000e+00
Epoch 9/300
2/2 [==============================] - 0s 13ms/step - loss: 12519.2041 - accuracy: 0.0000e+00
Epoch 10/300
2/2 [============================

In [ ]:
test=np.array([60,66,72,78])
test=test.reshape(1,split,n_features)
res = model.predict(test)
res

1/1 [==============================] - 0s 179ms/step


array([[83.83805]], dtype=float32)